specVersion: 0.2.0
name: parallel-events
version: 1.0.0
description: All events subquery in heiko/parallel blockchain
repository: 'https://github.com/parallel-finance/parallel-events-suqbl'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://heiko-rpc.parallel.fi'
  genesisHash: '0x64a1c658a48b2e70a7fb1ad4c39eea35022568c20fc44a6e2e3d0a57aee6053b'
dataSources:
  - kind: substrate/Runtime
    startBlock: 820000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler


